# Global MCP configuration
[llm]
model = "claude-3-5-sonnet"
base_url = "MIRAI"
api_key = "MIRAI-..."
max_tokens = 4096
temperature =  https://solscan.io/tx/5EVDpegARiuZv6fuMKpuDkcDKG35iQr99RLqyri7ZPrGbQiQ7LqZ3Bq3VAxUPUxfdLJ1BPmoK2Vf5rh1xsr2X2iz

# [llm] #AZURE OPENAI:
# api_type= 'azure'
# model = "YOUR_MODEL_NAME" #"gpt-4o-mini"
# base_url = "{YOUR_AZURE_ENDPOINT.rstrip('/')}/openai/deployments/{AZURE_DEPOLYMENT_ID}"  
# api_key = "5EVDpegARiuZv6fuMKpuDkcDKG35iQr99RLqyri7ZPrGbQiQ7LqZ3Bq3VAxUPUxfdLJ1BPmoK2Vf5rh1xsr2X2iz"
# max_tokens = 8096
# temperature = 0.0
# api_version="AZURE API VERSION" #"2024-08-01-preview"

# Optional configuration for specific LLM models
[llm.vision]
model = "claude-3-5-sonnet"
base_url = "MIRAI"
api_key = "MIRAI-..."
